source 'https://rubygems.org'

gem 'rails', '3.2.3'
gem 'mysql2'

gem 'jquery-rails'
gem 'haml'
gem 'coffee-filter'
gem 'devise'
gem "hashie"
gem "mustache"
gem "hamstache"
gem "poirot", :git => "git://github.com/theworkerant/poirot.git"
gem "json_pure"
gem 'bootstrap-sass', :git => "git://github.com/theworkerant/bootstrap-sass.git"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use debugger
gem 'ruby-debug19', :require => 'ruby-debug'
